# Configuracion del servidor
server.port=8080

# Configuracion de base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:tiendadb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar consola de H2 para visualizar datos por navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Crear y actualizar tablas automaticamente segun las entidades JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
